server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: playdata
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


