server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://34.41.53.216:3306/test?serverTimezone=Asia/Seoul
    username: playdata
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

