server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://my-mysql:3306/test?serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


