server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


