name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    environment: DOCKER
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 
        #이건 중요하진 않지만 잘 생각해야함?? 빌드만 할거면 이거 말고 핫스폿? 이런거 쓸 수 있음..
        
    - name: Permition
      run: chmod 744 gradlew

    - name: build
      run: ./gradlew clean build

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }} .
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      
      with:
        username: ${{ secrets.USERNAME }} #${{env.USERNAME}} 
        password: ${{ secrets.PASSWORD }}

    - name: DOCKER push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}

    - name: SSH Remote Commands
      # You may pin to the exact commit or the version.
      # uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{secrets.HOST_IP}}
        username: ${{secrets.HOST_USERNAME}}
        key: ${{secrets.HOST_KEY}} 
        script:
          #sudo su
          sudo docker stop ${{ secrets.DOCKER_REPOSITORY }}
          sudo docker rm ${{ secrets.DOCKER_REPOSITORY }}
          sudo docker run --name ${{ secrets.DOCKER_REPOSITORY }} -d -p 8080:8081 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
        
