name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: ${{secrets.DOCKER}}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 
        #이건 중요하진 않지만 잘 생각해야함?? 빌드만 할거면 이거 말고 핫스폿? 이런거 쓸 수 있음..
        
    - name: Permition
      run: chmod 744 gradlew

    - name: build
      run: ./gradlew clean build

    - name: Build the Docker image
      run: docker build -t testwoman/spring-test .
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      
      # with:
        # username: ${{secrets.DOCKER_USERNAME}}
        # password: ${{secrets.DOCKER_PASSWORD}}
